//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesDatavox2 : DbContext
    {
        public EntitiesDatavox2()
            : base("name=EntitiesDatavox2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Canal> tb_Canal { get; set; }
        public virtual DbSet<tb_Cliente> tb_Cliente { get; set; }
        public virtual DbSet<tb_Credito> tb_Credito { get; set; }
        public virtual DbSet<tb_CreditoObligacion> tb_CreditoObligacion { get; set; }
        public virtual DbSet<tb_CreditoPeriodoPago> tb_CreditoPeriodoPago { get; set; }
        public virtual DbSet<tb_CreditoSaldo> tb_CreditoSaldo { get; set; }
        public virtual DbSet<tb_CreditoTipoCalificacion> tb_CreditoTipoCalificacion { get; set; }
        public virtual DbSet<tb_CreditoTipoCredito> tb_CreditoTipoCredito { get; set; }
        public virtual DbSet<tb_CreditoTipoEstado> tb_CreditoTipoEstado { get; set; }
        public virtual DbSet<tb_CreditoTipoGarantia> tb_CreditoTipoGarantia { get; set; }
        public virtual DbSet<tb_CreditoTipoObligacion> tb_CreditoTipoObligacion { get; set; }
        public virtual DbSet<tb_Direccion> tb_Direccion { get; set; }
        public virtual DbSet<tb_Ejecutivo> tb_Ejecutivo { get; set; }
        public virtual DbSet<tb_Empresa> tb_Empresa { get; set; }
        public virtual DbSet<tb_EmpresaEstado> tb_EmpresaEstado { get; set; }
        public virtual DbSet<tb_EmpresaTipoCapital> tb_EmpresaTipoCapital { get; set; }
        public virtual DbSet<tb_EmpresaTipoClaseAccion> tb_EmpresaTipoClaseAccion { get; set; }
        public virtual DbSet<tb_EmpresaTipoParte> tb_EmpresaTipoParte { get; set; }
        public virtual DbSet<tb_EmpresaTipoRepresentacion> tb_EmpresaTipoRepresentacion { get; set; }
        public virtual DbSet<tb_EstadoFuente> tb_EstadoFuente { get; set; }
        public virtual DbSet<tb_Facturacion> tb_Facturacion { get; set; }
        public virtual DbSet<tb_Fuente> tb_Fuente { get; set; }
        public virtual DbSet<tb_Gentilicio> tb_Gentilicio { get; set; }
        public virtual DbSet<tb_HuellaBusqueda> tb_HuellaBusqueda { get; set; }
        public virtual DbSet<tb_HuellaConsulta> tb_HuellaConsulta { get; set; }
        public virtual DbSet<tb_HuellaMotivoConsulta> tb_HuellaMotivoConsulta { get; set; }
        public virtual DbSet<tb_HuellaTipoConsulta> tb_HuellaTipoConsulta { get; set; }
        public virtual DbSet<tb_Inmueble> tb_Inmueble { get; set; }
        public virtual DbSet<tb_InmuebleAnotaciones> tb_InmuebleAnotaciones { get; set; }
        public virtual DbSet<tb_InmuebleDerecho> tb_InmuebleDerecho { get; set; }
        public virtual DbSet<tb_InmuebleGarantia> tb_InmuebleGarantia { get; set; }
        public virtual DbSet<tb_InmuebleGravamen> tb_InmuebleGravamen { get; set; }
        public virtual DbSet<tb_InmuebleLinderos> tb_InmuebleLinderos { get; set; }
        public virtual DbSet<tb_InmuebleMatrices> tb_InmuebleMatrices { get; set; }
        public virtual DbSet<tb_InmuebleParteGravamen> tb_InmuebleParteGravamen { get; set; }
        public virtual DbSet<tb_InmuebleTipoDerecho> tb_InmuebleTipoDerecho { get; set; }
        public virtual DbSet<tb_InmuebleTipoOperacion> tb_InmuebleTipoOperacion { get; set; }
        public virtual DbSet<tb_InmuebleTipoPoderes> tb_InmuebleTipoPoderes { get; set; }
        public virtual DbSet<tb_InmuebleTipoProporcion> tb_InmuebleTipoProporcion { get; set; }
        public virtual DbSet<tb_Juicio> tb_Juicio { get; set; }
        public virtual DbSet<tb_Moneda> tb_Moneda { get; set; }
        public virtual DbSet<tb_Mueble> tb_Mueble { get; set; }
        public virtual DbSet<tb_MuebleDerecho> tb_MuebleDerecho { get; set; }
        public virtual DbSet<tb_MuebleGenCodigos> tb_MuebleGenCodigos { get; set; }
        public virtual DbSet<tb_MuebleGenTablas> tb_MuebleGenTablas { get; set; }
        public virtual DbSet<tb_MuebleGravamen> tb_MuebleGravamen { get; set; }
        public virtual DbSet<tb_MuebleInfracciones> tb_MuebleInfracciones { get; set; }
        public virtual DbSet<tb_MuebleLevantamientos> tb_MuebleLevantamientos { get; set; }
        public virtual DbSet<tb_MuebleParteGravamen> tb_MuebleParteGravamen { get; set; }
        public virtual DbSet<tb_MuebleTipoBien> tb_MuebleTipoBien { get; set; }
        public virtual DbSet<tb_MuebleTipoClaseBien> tb_MuebleTipoClaseBien { get; set; }
        public virtual DbSet<tb_MuebleTipoCodigoBien> tb_MuebleTipoCodigoBien { get; set; }
        public virtual DbSet<tb_MuebleVehiculo> tb_MuebleVehiculo { get; set; }
        public virtual DbSet<tb_Nicaraguenses> tb_Nicaraguenses { get; set; }
        public virtual DbSet<tb_Persona> tb_Persona { get; set; }
        public virtual DbSet<tb_PersonaEstadoCivilHistorico> tb_PersonaEstadoCivilHistorico { get; set; }
        public virtual DbSet<tb_PersonaEstadoId> tb_PersonaEstadoId { get; set; }
        public virtual DbSet<tb_PersonaPEPs> tb_PersonaPEPs { get; set; }
        public virtual DbSet<tb_PersonaTipoId> tb_PersonaTipoId { get; set; }
        public virtual DbSet<tb_PersonaTipoNacionalidad> tb_PersonaTipoNacionalidad { get; set; }
        public virtual DbSet<tb_PersonaTipoPersona> tb_PersonaTipoPersona { get; set; }
        public virtual DbSet<tb_PersonaTipoVinculo> tb_PersonaTipoVinculo { get; set; }
        public virtual DbSet<tb_PersonaVinculo> tb_PersonaVinculo { get; set; }
        public virtual DbSet<tb_Producto> tb_Producto { get; set; }
        public virtual DbSet<tb_SalarioActualizacion> tb_SalarioActualizacion { get; set; }
        public virtual DbSet<tb_SalarioHistorico> tb_SalarioHistorico { get; set; }
        public virtual DbSet<tb_Sector> tb_Sector { get; set; }
        public virtual DbSet<tb_Sexo> tb_Sexo { get; set; }
        public virtual DbSet<tb_Telefono> tb_Telefono { get; set; }
        public virtual DbSet<tb_TipoDireccion> tb_TipoDireccion { get; set; }
        public virtual DbSet<tb_TipoEstadoCivil> tb_TipoEstadoCivil { get; set; }
        public virtual DbSet<tb_TipoPersonaJuridica> tb_TipoPersonaJuridica { get; set; }
        public virtual DbSet<tb_TipoReport> tb_TipoReport { get; set; }
        public virtual DbSet<tb_TipoTelefono> tb_TipoTelefono { get; set; }
        public virtual DbSet<tb_Usuario> tb_Usuario { get; set; }
        public virtual DbSet<DerechosMueblesExp> DerechosMueblesExp { get; set; }
        public virtual DbSet<tb_DivisionTerritorial> tb_DivisionTerritorial { get; set; }
        public virtual DbSet<tb_MuebleAeronave> tb_MuebleAeronave { get; set; }
        public virtual DbSet<tb_MuebleBuque> tb_MuebleBuque { get; set; }
        public virtual DbSet<tb_MuebleGarantia> tb_MuebleGarantia { get; set; }
        public virtual DbSet<tb_MuebleMotores> tb_MuebleMotores { get; set; }
        public virtual DbSet<tb_PersonaIdentificacion> tb_PersonaIdentificacion { get; set; }
        public virtual DbSet<tb_Salario> tb_Salario { get; set; }
        public virtual DbSet<tb_SalarioPatrono> tb_SalarioPatrono { get; set; }
        public virtual DbSet<tb_TelefonoPersona> tb_TelefonoPersona { get; set; }
    }
}
