//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Credito
    {
        public int ConsecutivoCredito { get; set; }
        public string NumeroCredito { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> FechaOtorgamiento { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<System.DateTime> FechaUltPago { get; set; }
        public Nullable<short> IdTipoOperacion { get; set; }
        public Nullable<short> IdTipoCredito { get; set; }
        public Nullable<short> IdTipoGarantia { get; set; }
        public Nullable<short> IdPeriodoPago { get; set; }
        public Nullable<System.DateTime> FechaIncobrable { get; set; }
        public Nullable<bool> EsOculto { get; set; }
        public Nullable<System.DateTime> FechaOculto { get; set; }
        public Nullable<int> IdFuente { get; set; }
        public Nullable<int> IdFuenteOculto { get; set; }
    
        public virtual tb_Cliente tb_Cliente { get; set; }
        public virtual tb_CreditoPeriodoPago tb_CreditoPeriodoPago { get; set; }
        public virtual tb_CreditoTipoCredito tb_CreditoTipoCredito { get; set; }
        public virtual tb_CreditoTipoGarantia tb_CreditoTipoGarantia { get; set; }
        public virtual tb_Fuente tb_Fuente { get; set; }
    }
}
