//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Cliente()
        {
            this.tb_Credito = new HashSet<tb_Credito>();
            this.tb_HuellaBusqueda = new HashSet<tb_HuellaBusqueda>();
            this.tb_HuellaConsulta = new HashSet<tb_HuellaConsulta>();
        }
    
        public int IdCliente { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdSector { get; set; }
        public string ClienteEstado { get; set; }
        public string FechaAfiliacion { get; set; }
        public string FechaDesafiliacion { get; set; }
        public Nullable<byte> NivelReciprocidad { get; set; }
        public Nullable<short> IdEjecutivo { get; set; }
        public Nullable<bool> EsInterno { get; set; }
        public Nullable<bool> EsCallCenter { get; set; }
        public Nullable<bool> EsSupervisado { get; set; }
        public Nullable<bool> CanceladoAutomaticoHC { get; set; }
        public Nullable<bool> CanceladoAutomaticoTC { get; set; }
    
        public virtual tb_Ejecutivo tb_Ejecutivo { get; set; }
        public virtual tb_Empresa tb_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Credito> tb_Credito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HuellaBusqueda> tb_HuellaBusqueda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HuellaConsulta> tb_HuellaConsulta { get; set; }
    }
}
