//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CreditoTipoGarantia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_CreditoTipoGarantia()
        {
            this.tb_Credito = new HashSet<tb_Credito>();
        }
    
        public short IdGarantia { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Credito> tb_Credito { get; set; }
        public virtual tb_CreditoTipoGarantia tb_CreditoTipoGarantia1 { get; set; }
        public virtual tb_CreditoTipoGarantia tb_CreditoTipoGarantia2 { get; set; }
    }
}
