//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CreditoSaldo
    {
        public int ConsecutivoCredito { get; set; }
        public Nullable<decimal> MontoOtorgado { get; set; }
        public Nullable<decimal> SaldoActual { get; set; }
        public Nullable<decimal> SaldoMora { get; set; }
        public Nullable<short> IndiceMora { get; set; }
        public Nullable<decimal> ValorCuota { get; set; }
        public Nullable<short> CantidadCuotasVencidas { get; set; }
        public Nullable<int> DiasMora { get; set; }
        public short IdMoneda { get; set; }
        public Nullable<short> IdCalificacion { get; set; }
        public Nullable<short> IdCreditoEstado { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
    }
}
