//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CreditoTipoEstado
    {
        public short IdEstado { get; set; }
        public string DescripcionEstado { get; set; }
        public string SiglaEstado { get; set; }
        public string SiglaSubEstado { get; set; }
        public Nullable<short> PrioridadEstado { get; set; }
    }
}
