//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Direccion
    {
        public int IdDireccion { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
        public string DistritoAdministrativo { get; set; }
        public string DistritoElectoral { get; set; }
        public string Direccion { get; set; }
        public Nullable<short> TipoDireccion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_TipoDireccion tb_TipoDireccion { get; set; }
    }
}
