//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DivisionTerritorial
    {
        public string Codigo { get; set; }
        public string CodProvincia { get; set; }
        public string CodCanton { get; set; }
        public string CodDistritoAdm { get; set; }
        public string CodDistritoElec { get; set; }
        public string NombreProvincia { get; set; }
        public string NombreCanton { get; set; }
        public string NombreDistritoAdm { get; set; }
        public string NombreDistritoElec { get; set; }
    }
}
