//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Empresa()
        {
            this.tb_Cliente = new HashSet<tb_Cliente>();
        }
    
        public int idPersona { get; set; }
        public string NombreComercial { get; set; }
        public Nullable<int> TipoPersonaJuridica { get; set; }
        public Nullable<short> IndOtorgaPoderes { get; set; }
        public string TomoInscripcion { get; set; }
        public string FolioInscripcion { get; set; }
        public string AsientoInscripcion { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string IdEstadoActual { get; set; }
        public string FinesEmpresa { get; set; }
        public string Prorrogas { get; set; }
        public string DescProrrogas { get; set; }
        public string Representacion { get; set; }
        public string SectorEmpresa { get; set; }
        public string SectorEconomicoEmpresa { get; set; }
        public Nullable<int> IdFuente { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaAct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Cliente> tb_Cliente { get; set; }
        public virtual tb_EmpresaEstado tb_EmpresaEstado { get; set; }
        public virtual tb_TipoPersonaJuridica tb_TipoPersonaJuridica { get; set; }
    }
}
