//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Fuente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Fuente()
        {
            this.tb_Credito = new HashSet<tb_Credito>();
        }
    
        public int IdFuente { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Usuario { get; set; }
        public string Equipo { get; set; }
        public string Origen { get; set; }
        public Nullable<int> IdPaquete { get; set; }
        public Nullable<short> IdEstadoFuente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Credito> tb_Credito { get; set; }
        public virtual tb_EstadoFuente tb_EstadoFuente { get; set; }
    }
}
