//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HuellaConsulta
    {
        public long IdHuellaConsulta { get; set; }
        public long IdHuellaBusqueda { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public short IdMotivoConsulta { get; set; }
        public string Cobrable { get; set; }
        public int IdPersona { get; set; }
        public string Respuesta { get; set; }
        public int IdCliente { get; set; }
        public int IdProducto { get; set; }
        public int TiempoRespuesta { get; set; }
    
        public virtual tb_Cliente tb_Cliente { get; set; }
        public virtual tb_HuellaBusqueda tb_HuellaBusqueda { get; set; }
        public virtual tb_HuellaMotivoConsulta tb_HuellaMotivoConsulta { get; set; }
        public virtual tb_Persona tb_Persona { get; set; }
        public virtual tb_Producto tb_Producto { get; set; }
    }
}
