//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HuellaBusqueda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_HuellaBusqueda()
        {
            this.tb_HuellaConsulta = new HashSet<tb_HuellaConsulta>();
        }
    
        public long IdHuellaBusqueda { get; set; }
        public System.DateTime FechaBusqueda { get; set; }
        public byte IdCanal { get; set; }
        public int IdProducto { get; set; }
        public int IdCliente { get; set; }
        public int IdUsuario { get; set; }
        public string IpServidor { get; set; }
        public bool PersonaHit { get; set; }
        public byte IdTipoConsulta { get; set; }
    
        public virtual tb_Canal tb_Canal { get; set; }
        public virtual tb_Cliente tb_Cliente { get; set; }
        public virtual tb_Producto tb_Producto { get; set; }
        public virtual tb_HuellaTipoConsulta tb_HuellaTipoConsulta { get; set; }
        public virtual tb_Usuario tb_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HuellaConsulta> tb_HuellaConsulta { get; set; }
    }
}
