//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_InmuebleTipoOperacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_InmuebleTipoOperacion()
        {
            this.tb_InmuebleDerecho = new HashSet<tb_InmuebleDerecho>();
            this.tb_InmuebleGravamen = new HashSet<tb_InmuebleGravamen>();
        }
    
        public string IdOperacion { get; set; }
        public string Causa { get; set; }
        public Nullable<short> ClaseCausa { get; set; }
        public Nullable<short> RutinaCalculo { get; set; }
        public string DescripcionOperacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleDerecho> tb_InmuebleDerecho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleGravamen> tb_InmuebleGravamen { get; set; }
    }
}
