//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_InmuebleGravamen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_InmuebleGravamen()
        {
            this.tb_InmuebleGarantia = new HashSet<tb_InmuebleGarantia>();
            this.tb_InmuebleParteGravamen = new HashSet<tb_InmuebleParteGravamen>();
        }
    
        public int idGravamen { get; set; }
        public Nullable<int> idGarantía { get; set; }
        public string TomoGravamen { get; set; }
        public string AsientoGravamen { get; set; }
        public string ConsecGravamen { get; set; }
        public string SecuenciaGravamen { get; set; }
        public string SubsecuenciaGravamen { get; set; }
        public Nullable<short> IdMoneda { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> FechaInicia { get; set; }
        public Nullable<System.DateTime> FechaVence { get; set; }
        public Nullable<System.DateTime> FechaInterrupcion { get; set; }
        public Nullable<short> CantRenuncias { get; set; }
        public Nullable<short> CantCedulasHipotecarias { get; set; }
        public Nullable<short> UltSecuenciaParte { get; set; }
        public string IdTipoOperacion { get; set; }
        public string Presentacion { get; set; }
        public Nullable<System.DateTime> FechaUltActualizacion { get; set; }
        public string CitasAntecedentes { get; set; }
        public Nullable<decimal> AreaArrendada { get; set; }
        public string FormaPago { get; set; }
        public string Interes { get; set; }
        public Nullable<decimal> AreaResto { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleGarantia> tb_InmuebleGarantia { get; set; }
        public virtual tb_InmuebleTipoOperacion tb_InmuebleTipoOperacion { get; set; }
        public virtual tb_Moneda tb_Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleParteGravamen> tb_InmuebleParteGravamen { get; set; }
    }
}
