//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_InmuebleLinderos
    {
        public int IdLindero { get; set; }
        public int IdInmueble { get; set; }
        public string Provincia { get; set; }
        public string Numero { get; set; }
        public string Duplicado { get; set; }
        public string Horizontal { get; set; }
        public string PuntoCardinal { get; set; }
        public string Lindero { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_Inmueble tb_Inmueble { get; set; }
    }
}
