//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_InmuebleGarantia
    {
        public int IdGarantia { get; set; }
        public int idGravamen { get; set; }
        public int IdInmueble { get; set; }
        public string TomoGravamen { get; set; }
        public string AsientoGravamen { get; set; }
        public string ConsecGravamen { get; set; }
        public string SecuenciaGravamen { get; set; }
        public string SubSecuenciaGravamen { get; set; }
        public string ClaseResponsabilidad { get; set; }
        public Nullable<short> TomoCredito { get; set; }
        public Nullable<int> AsientoCredito { get; set; }
        public Nullable<short> ConsecutivoCredito { get; set; }
        public Nullable<short> SecuenciaCredito { get; set; }
        public Nullable<short> SubsecuenciaCredito { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<short> Grado { get; set; }
        public string Base_Remate { get; set; }
        public string Referencia_Finca { get; set; }
        public string Referencia_Gravamen { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_Inmueble tb_Inmueble { get; set; }
        public virtual tb_InmuebleGravamen tb_InmuebleGravamen { get; set; }
    }
}
