//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Inmueble
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Inmueble()
        {
            this.tb_InmuebleDerecho = new HashSet<tb_InmuebleDerecho>();
            this.tb_InmuebleGarantia = new HashSet<tb_InmuebleGarantia>();
            this.tb_InmuebleLinderos = new HashSet<tb_InmuebleLinderos>();
            this.tb_InmuebleMatrices = new HashSet<tb_InmuebleMatrices>();
        }
    
        public int IdInmueble { get; set; }
        public string Provincia { get; set; }
        public string Numero { get; set; }
        public string Duplicado { get; set; }
        public string Horizontal { get; set; }
        public string NumeroFinca { get; set; }
        public string Canton { get; set; }
        public string Distrito { get; set; }
        public Nullable<decimal> Medida { get; set; }
        public Nullable<short> UltimoDerecho { get; set; }
        public string IdOperacion { get; set; }
        public string Presentacion { get; set; }
        public Nullable<System.DateTime> FechaUltActualizacion { get; set; }
        public string Naturaleza { get; set; }
        public string Status { get; set; }
        public string Plano { get; set; }
        public string NumeroCatastral { get; set; }
        public Nullable<decimal> Avaluo { get; set; }
        public Nullable<decimal> ValorPorcentual { get; set; }
        public string IndicadorSegregacion { get; set; }
        public string IdProvincia2 { get; set; }
        public string IdCanton2 { get; set; }
        public string IdDistrito2 { get; set; }
        public Nullable<decimal> ValorMedida { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaAct { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleDerecho> tb_InmuebleDerecho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleGarantia> tb_InmuebleGarantia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleLinderos> tb_InmuebleLinderos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleMatrices> tb_InmuebleMatrices { get; set; }
    }
}
