//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_InmuebleDerecho
    {
        public int IdDerecho { get; set; }
        public int IdInmueble { get; set; }
        public string NumeroFinca { get; set; }
        public int IdPersona { get; set; }
        public Nullable<short> Derecho { get; set; }
        public Nullable<short> IdMoneda { get; set; }
        public Nullable<decimal> MontoContrato { get; set; }
        public string IdTipoDerecho { get; set; }
        public string idTipoOperacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaAct { get; set; }
        public string IdProporcion { get; set; }
        public Nullable<decimal> ValorProporcion1 { get; set; }
        public Nullable<decimal> ValorProporcion2 { get; set; }
        public string CausaAdquisitiva { get; set; }
        public string FormaPago { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_Inmueble tb_Inmueble { get; set; }
        public virtual tb_InmuebleTipoDerecho tb_InmuebleTipoDerecho { get; set; }
        public virtual tb_InmuebleTipoOperacion tb_InmuebleTipoOperacion { get; set; }
        public virtual tb_InmuebleTipoProporcion tb_InmuebleTipoProporcion { get; set; }
        public virtual tb_Moneda tb_Moneda { get; set; }
        public virtual tb_Persona tb_Persona { get; set; }
    }
}
