//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_InmuebleAnotaciones
    {
        public int idAnotacion { get; set; }
        public string CitaAnotacion { get; set; }
        public string TipoOperacion { get; set; }
        public Nullable<System.DateTime> FechaAnotacion { get; set; }
        public Nullable<int> IdInmueble { get; set; }
        public Nullable<short> Derecho { get; set; }
        public Nullable<int> IdGravamen { get; set; }
        public Nullable<short> SecuenciaAfectada { get; set; }
        public string CreditoAsociado { get; set; }
        public Nullable<int> IdFuente { get; set; }
    }
}
