//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_InmuebleMatrices
    {
        public int IdMatriz { get; set; }
        public int IdInmueble { get; set; }
        public int IdPersona { get; set; }
        public string Provincia { get; set; }
        public string Numero { get; set; }
        public string Duplicado { get; set; }
        public string Horizontal { get; set; }
        public Nullable<System.DateTime> InicioAdm { get; set; }
        public Nullable<System.DateTime> VenceAdm { get; set; }
        public Nullable<short> IdPoder { get; set; }
        public Nullable<short> Filiales { get; set; }
        public Nullable<decimal> AreaComun { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<short> IdMoneda { get; set; }
        public string NombreCondominio { get; set; }
        public Nullable<int> IdPersonaJuridica { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_Inmueble tb_Inmueble { get; set; }
        public virtual tb_Persona tb_Persona { get; set; }
        public virtual tb_InmuebleTipoPoderes tb_InmuebleTipoPoderes { get; set; }
        public virtual tb_Moneda tb_Moneda { get; set; }
        public virtual tb_Persona tb_Persona1 { get; set; }
    }
}
