//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Juicio
    {
        public int IdJuicio { get; set; }
        public string Expediente { get; set; }
        public string Descrpcion { get; set; }
        public string Caso { get; set; }
        public string Asunto { get; set; }
        public Nullable<decimal> Cuantia { get; set; }
        public string MonedaCuantia { get; set; }
        public string Oficina { get; set; }
        public string Circuito { get; set; }
        public string Sentencia { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaEstado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaAct { get; set; }
        public Nullable<int> IdFuente { get; set; }
        public string TempId { get; set; }
        public Nullable<bool> EsOculto { get; set; }
        public Nullable<System.DateTime> FechaOculto { get; set; }
    }
}
