//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MuebleMotores
    {
        public int IdMueble { get; set; }
        public string NumeroMotor { get; set; }
        public string Marca { get; set; }
        public string Procedencia { get; set; }
        public string Combustible { get; set; }
        public Nullable<short> NumeroCilindros { get; set; }
        public Nullable<decimal> Cilindrada { get; set; }
        public Nullable<decimal> Potencia { get; set; }
        public string Modelo { get; set; }
        public string NumeroSerie { get; set; }
        public string NombreFabricante { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_Mueble tb_Mueble { get; set; }
    }
}
