//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MuebleGarantia
    {
        public int IdGravamen { get; set; }
        public Nullable<int> IdMueble { get; set; }
        public string NumeroGarantia { get; set; }
        public string NumeroDerecho { get; set; }
        public string TomoGravamenAfectado { get; set; }
        public string AsientoGravamenAfectado { get; set; }
        public string SecuenciaGravamenAfectado { get; set; }
        public string TipoGarantia { get; set; }
        public string GradoGarantia { get; set; }
        public string TomoConstitucion { get; set; }
        public string AsientoConstitucion { get; set; }
        public string SecuenciaConstitucion { get; set; }
        public string NumeroFinca { get; set; }
        public string AnoAgricola { get; set; }
        public string EstadoGarantia { get; set; }
        public Nullable<decimal> ProporcionMonto { get; set; }
        public string DescripcionGarantia { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_MuebleGravamen tb_MuebleGravamen { get; set; }
    }
}
