//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Mueble
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Mueble()
        {
            this.tb_MuebleDerecho = new HashSet<tb_MuebleDerecho>();
            this.tb_MuebleInfracciones = new HashSet<tb_MuebleInfracciones>();
            this.tb_MuebleLevantamientos = new HashSet<tb_MuebleLevantamientos>();
        }
    
        public int IdMueble { get; set; }
        public string Placa { get; set; }
        public string TipoBien { get; set; }
        public string ClaseBien { get; set; }
        public string CodigoBien { get; set; }
        public string NumeroBien { get; set; }
        public Nullable<decimal> NumeroRegistral { get; set; }
        public string TomoInscripcion { get; set; }
        public string AsientoInscripcion { get; set; }
        public string SecuenciaInscripcion { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public string NumIdAnterior { get; set; }
        public string CitasAnteriores { get; set; }
        public Nullable<decimal> ValorHaciendaInscripcion { get; set; }
        public Nullable<decimal> ValorHaciendaOficial { get; set; }
        public Nullable<decimal> ValorContrato { get; set; }
        public string EstadoActual { get; set; }
        public string EstadoActualTributario { get; set; }
        public string Uso { get; set; }
        public string TomoUltMovimiento { get; set; }
        public string AsientoUltMovimiento { get; set; }
        public string SecuenciaUltMovimiento { get; set; }
        public string FechaUltMovimiento { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_MuebleTipoBien tb_MuebleTipoBien { get; set; }
        public virtual tb_MuebleAeronave tb_MuebleAeronave { get; set; }
        public virtual tb_MuebleBuque tb_MuebleBuque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MuebleDerecho> tb_MuebleDerecho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MuebleInfracciones> tb_MuebleInfracciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MuebleLevantamientos> tb_MuebleLevantamientos { get; set; }
        public virtual tb_MuebleMotores tb_MuebleMotores { get; set; }
        public virtual tb_MuebleVehiculo tb_MuebleVehiculo { get; set; }
    }
}
