//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MuebleVehiculo
    {
        public int IdMueble { get; set; }
        public string Marca { get; set; }
        public Nullable<int> AnoFabricacion { get; set; }
        public string Estilo { get; set; }
        public string Categoria { get; set; }
        public string TipoBien { get; set; }
        public string NumeroChasis { get; set; }
        public string NumeroSerie { get; set; }
        public string Carroceria { get; set; }
        public Nullable<short> CapacidadPasajeros { get; set; }
        public Nullable<decimal> PesoNeto { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public Nullable<decimal> PesoRemolque { get; set; }
        public Nullable<decimal> PesoVacio { get; set; }
        public string Color { get; set; }
        public string Traccion { get; set; }
        public string NumeroVIN { get; set; }
        public string TipoCabina { get; set; }
        public string TipoTecho { get; set; }
        public Nullable<short> NumeroEjes { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string IndicadorRefaccion { get; set; }
        public string IndicadorConvertido { get; set; }
        public Nullable<decimal> ClaseTributaria { get; set; }
    
        public virtual tb_Mueble tb_Mueble { get; set; }
    }
}
