//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MuebleInfracciones
    {
        public int IdInfraccion { get; set; }
        public int IdMueble { get; set; }
        public string IdAutoridadJudicial { get; set; }
        public string NumeroSumaria { get; set; }
        public string NumeroBoleta { get; set; }
        public Nullable<System.DateTime> FechaBoleta { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> HoraRegistro { get; set; }
        public string IdTipoGravamen { get; set; }
        public string AutoridadJudicial { get; set; }
        public string Obsrvaciones { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_Mueble tb_Mueble { get; set; }
    }
}
