//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MuebleAeronave
    {
        public int IdMueble { get; set; }
        public Nullable<decimal> AnoFabricacion { get; set; }
        public string TipoAeronave { get; set; }
        public string NumeroSerie { get; set; }
        public string Estilo { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public Nullable<decimal> ClaseTributaria { get; set; }
        public Nullable<decimal> PesoMaximo { get; set; }
        public Nullable<decimal> PesoVacio { get; set; }
        public string Fabricante { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_Mueble tb_Mueble { get; set; }
    }
}
