//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MuebleTipoCodigoBien
    {
        public string TipoBien { get; set; }
        public string ClaseBien { get; set; }
        public string CodigoBien { get; set; }
        public string UltConsecutivo { get; set; }
        public string Descripcion { get; set; }
        public string IndicadorHabilitado { get; set; }
        public string DescripcionCorta { get; set; }
    }
}
