//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MuebleDerecho
    {
        public int IdDerechoMueble { get; set; }
        public int IdMueble { get; set; }
        public int IdPersona { get; set; }
        public string NumeroDerecho { get; set; }
        public string TomoAdquisicion { get; set; }
        public string AsientoAdquisicion { get; set; }
        public string SecuentaAdquisicion { get; set; }
        public string TipoDerecho { get; set; }
        public string CausaAdquisitiva { get; set; }
        public Nullable<decimal> Proporcion1 { get; set; }
        public Nullable<decimal> Proporcion2 { get; set; }
        public Nullable<System.DateTime> FechaAdquisicion { get; set; }
        public Nullable<System.DateTime> FechaConstitucion { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_Mueble tb_Mueble { get; set; }
        public virtual tb_Persona tb_Persona { get; set; }
    }
}
