//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MuebleBuque
    {
        public int IdMueble { get; set; }
        public string IdMarca { get; set; }
        public string IdActividad { get; set; }
        public string NumeroSerie { get; set; }
        public Nullable<int> AnoConstruccion { get; set; }
        public Nullable<decimal> PesoNeto { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public Nullable<decimal> NumeroEslora { get; set; }
        public Nullable<decimal> NumeroManga { get; set; }
        public Nullable<decimal> NumeroPuntal { get; set; }
        public string Estilo { get; set; }
        public string NumeroCasco { get; set; }
        public string NombreBuque { get; set; }
        public string NumeroChasis { get; set; }
        public string NombreConstructor { get; set; }
        public string LugarConstruccion { get; set; }
        public string DescripcionCasco { get; set; }
        public Nullable<int> IdFuente { get; set; }
    
        public virtual tb_Mueble tb_Mueble { get; set; }
    }
}
