//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Nicaraguenses
    {
        public int IdNicaraguense { get; set; }
        public Nullable<short> IdTipoPersona { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<byte> IdSexo { get; set; }
        public Nullable<short> IdEstadoCivil { get; set; }
        public string EstadoVida { get; set; }
        public string Identificacion { get; set; }
        public Nullable<short> IdTipoIdentificacion { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string EstadoIdentificacion { get; set; }
        public string Departamento { get; set; }
        public string Municipio { get; set; }
        public Nullable<decimal> IngresoRegistrado { get; set; }
        public string RangoIngreso { get; set; }
        public Nullable<System.DateTime> FechaActIngreso { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> Fuente { get; set; }
    
        public virtual tb_TipoEstadoCivil tb_TipoEstadoCivil { get; set; }
        public virtual tb_Sexo tb_Sexo { get; set; }
        public virtual tb_Nicaraguenses tb_Nicaraguenses1 { get; set; }
        public virtual tb_Nicaraguenses tb_Nicaraguenses2 { get; set; }
        public virtual tb_PersonaTipoId tb_PersonaTipoId { get; set; }
        public virtual tb_PersonaTipoPersona tb_PersonaTipoPersona { get; set; }
    }
}
