//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PersonaEstadoCivilHistorico
    {
        public int IdEvento { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdPersonaConyuge { get; set; }
        public string CitaMatrimonio { get; set; }
        public string NombreCoyugue { get; set; }
        public Nullable<short> TipoSuceso { get; set; }
        public Nullable<short> TipoMatrimonio { get; set; }
        public Nullable<System.DateTime> FechaSuceso { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public Nullable<short> ProvinciaSuceso { get; set; }
        public Nullable<short> CantonSuceso { get; set; }
        public Nullable<short> DistritoSuceso { get; set; }
        public string LugarSuceso { get; set; }
        public Nullable<bool> EsOculto { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<System.DateTime> FechaOculto { get; set; }
        public Nullable<int> IdFuente { get; set; }
    }
}
