//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PersonaPEPs
    {
        public int IdPersonaPeps { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public string Identificacion { get; set; }
        public string NombreCompleto { get; set; }
        public string Institucion { get; set; }
        public string Cargo { get; set; }
        public string Periodo { get; set; }
    
        public virtual tb_Persona tb_Persona { get; set; }
    }
}
