//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PersonaTipoId
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PersonaTipoId()
        {
            this.tb_Nicaraguenses = new HashSet<tb_Nicaraguenses>();
            this.tb_PersonaIdentificacion = new HashSet<tb_PersonaIdentificacion>();
        }
    
        public short IdIdentificacionTipo { get; set; }
        public string NombreIdentificacion { get; set; }
        public string Sigla { get; set; }
        public Nullable<bool> IdFisico { get; set; }
        public Nullable<bool> IdJuridico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Nicaraguenses> tb_Nicaraguenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PersonaIdentificacion> tb_PersonaIdentificacion { get; set; }
    }
}
