//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Persona()
        {
            this.tb_HuellaConsulta = new HashSet<tb_HuellaConsulta>();
            this.tb_InmuebleDerecho = new HashSet<tb_InmuebleDerecho>();
            this.tb_InmuebleMatrices = new HashSet<tb_InmuebleMatrices>();
            this.tb_InmuebleMatrices1 = new HashSet<tb_InmuebleMatrices>();
            this.tb_InmuebleParteGravamen = new HashSet<tb_InmuebleParteGravamen>();
            this.tb_MuebleDerecho = new HashSet<tb_MuebleDerecho>();
            this.tb_PersonaIdentificacion = new HashSet<tb_PersonaIdentificacion>();
            this.tb_PersonaVinculo = new HashSet<tb_PersonaVinculo>();
            this.tb_PersonaVinculo1 = new HashSet<tb_PersonaVinculo>();
            this.tb_Salario = new HashSet<tb_Salario>();
            this.tb_TelefonoPersona = new HashSet<tb_TelefonoPersona>();
        }
    
        public int IdPersona { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<short> IdTipoPersona { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaConstitucionJuridico { get; set; }
        public string IdSexo { get; set; }
        public Nullable<short> IdEstadoCivil { get; set; }
        public Nullable<short> Nacionalidad { get; set; }
        public string EstadoVida { get; set; }
        public Nullable<short> IdOcupacion { get; set; }
        public string LugarNacimiento { get; set; }
        public Nullable<System.DateTime> FechaDefuncion { get; set; }
        public Nullable<short> IdGentilicio { get; set; }
        public string ConocidoComo { get; set; }
        public string TipoAsegurado { get; set; }
        public string EsOculto { get; set; }
        public string FechaOculto { get; set; }
        public Nullable<int> idFuente { get; set; }
        public string IdTemp { get; set; }
        public Nullable<System.DateTime> FechaNaturalizacion { get; set; }
        public string NombrePadre { get; set; }
        public string NombreMadre { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaAct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HuellaConsulta> tb_HuellaConsulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleDerecho> tb_InmuebleDerecho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleMatrices> tb_InmuebleMatrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleMatrices> tb_InmuebleMatrices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InmuebleParteGravamen> tb_InmuebleParteGravamen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MuebleDerecho> tb_MuebleDerecho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PersonaIdentificacion> tb_PersonaIdentificacion { get; set; }
        public virtual tb_PersonaPEPs tb_PersonaPEPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PersonaVinculo> tb_PersonaVinculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PersonaVinculo> tb_PersonaVinculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Salario> tb_Salario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TelefonoPersona> tb_TelefonoPersona { get; set; }
    }
}
