//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PersonaIdentificacion
    {
        public int IdPersona { get; set; }
        public string Identificacion { get; set; }
        public short IdIdentificacionTipo { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> IdUbicacionGeo1 { get; set; }
        public Nullable<int> IdUbicacionGeo2 { get; set; }
        public Nullable<int> IdUbicacionGeo3 { get; set; }
        public Nullable<short> IdentificacionEstado { get; set; }
        public Nullable<int> IdFuente { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaAct { get; set; }
    
        public virtual tb_Persona tb_Persona { get; set; }
        public virtual tb_PersonaEstadoId tb_PersonaEstadoId { get; set; }
        public virtual tb_PersonaTipoId tb_PersonaTipoId { get; set; }
    }
}
