//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SalarioHistorico
    {
        public int idSalario { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public Nullable<int> Salario { get; set; }
        public Nullable<int> IdPersonaEmpleado { get; set; }
        public Nullable<int> IdPersonaPatrono { get; set; }
        public Nullable<int> IdActualizacion { get; set; }
        public Nullable<int> IdFuente { get; set; }
        public Nullable<bool> EsOculto { get; set; }
        public Nullable<System.DateTime> FechaOculto { get; set; }
    
        public virtual tb_SalarioActualizacion tb_SalarioActualizacion { get; set; }
    }
}
