//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SalarioPatrono
    {
        public int idPatrono { get; set; }
        public Nullable<int> IdPersonaEmpleado { get; set; }
        public Nullable<int> IdFuente { get; set; }
    }
}
