//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Telefono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Telefono()
        {
            this.tb_TelefonoPersona = new HashSet<tb_TelefonoPersona>();
        }
    
        [JsonIgnore]
        public int idTelefono { get; set; }
        public string Tipo { get; set; }
        public string Telefono { get; set; }
        [JsonIgnore]

        public Nullable<short> TipoTelefono { get; set; }
        [JsonIgnore]

        public Nullable<int> idFuente { get; set; }
        [JsonIgnore]

        public Nullable<int> TempId { get; set; }
        [JsonIgnore]

        public virtual tb_TipoTelefono tb_TipoTelefono { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]

        public virtual ICollection<tb_TelefonoPersona> tb_TelefonoPersona { get; set; }
    }
}
