//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TipoPersonaJuridica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_TipoPersonaJuridica()
        {
            this.tb_Empresa = new HashSet<tb_Empresa>();
        }
    
        public int IdTipoPersonaJuridica { get; set; }
        public string CodigoTipoCedula { get; set; }
        public string DescripcionTipo { get; set; }
        public string CodigoClaseCedula { get; set; }
        public string DescripcionClase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Empresa> tb_Empresa { get; set; }
        public virtual tb_TipoPersonaJuridica tb_TipoPersonaJuridica1 { get; set; }
        public virtual tb_TipoPersonaJuridica tb_TipoPersonaJuridica2 { get; set; }
    }
}
